language: node_js
node_js_:
  - "12.13.0"
install:
  - npm install -g firebase-tools
after-success:
  -firebase deploy --token 1//066cJLbzffAC5CgYIARAAGAYSNwF-L9Ir70QKXLTI8mp4IJeFcKOJVfzNQB6BBB8YP4ylTjAuHaeKYmipGbFeJ2LgAIukJb3U9Pc